name: tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Prepare container
        run: apk update && apk add bats neovim git

      - name: Checkout repositry
        run: git clone --depth 1 "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" ./

      - name: Run tests
        run: bats ./tests/main.bats
